services:
  app:
    labels:
      - "traefik.http.routers.rekkoo-prod.rule=Host(`rekkoo.com`) || Host(`www.rekkoo.com`)"
      - "traefik.http.routers.rekkoo-prod.entrypoints=websecure"
      - "traefik.http.routers.rekkoo-prod.service=rekkoo-prod"
      - "traefik.http.routers.rekkoo-prod.tls=true"
      - "traefik.http.routers.rekkoo-prod.tls.certresolver=letsencrypt"
