name: rekkoo-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use specific dev Dockerfile
    container_name: rekkoo-dev-app
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      # Add node_modules volume to prevent overwriting by host mount
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.rekkoo-dev.rule=Host(`rekkoo.local`)"
      - "traefik.http.routers.rekkoo-dev.entrypoints=web"
      - "traefik.http.services.rekkoo-dev.loadbalancer.server.port=5174"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
