name: rekkoo-prod

services:
  app:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: rekkoo-prod-app
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: proxy
