name: rekkoo-dev

services:
  app:
    container_name: rekkoo-dev-app
    env_file:
      - .env.local
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo.loadbalancer.server.port=80"
      - "traefik.http.routers.rekkoo.rule=Host(`rekkoo.local`)"
