# docker-compose.local.yml (for local development)
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rekkoo-local
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo-local.loadbalancer.server.port=5174"
      # Match when env=local is present, regardless of remote parameter
      - "traefik.http.routers.rekkoo-local.rule=Host(`dev.rekkoo.com`) && Query(`env=local`)"
      - "traefik.http.routers.rekkoo-local.entrypoints=web"
