name: rekkoo-prod

services:
  app:
    image: rekkoo-app:latest  # This will use the saved/loaded image in production
    container_name: rekkoo-prod-app
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: proxy
