name: rekkoo-${DEPLOY_ENV}

services:
  app:
    image: rekkoo-app-${DEPLOY_ENV}-${SAFE_BRANCH_NAME}:latest  # This matches what CI builds
    container_name: rekkoo-${DEPLOY_ENV}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo-${DEPLOY_ENV}.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
