services:
  rekkoo-web:
    image: ${IMAGE_NAME:-rekkoo-app-prod-main:latest}
    platform: linux/amd64
    container_name: rekkoo-web-prod
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo-web-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.rekkoo-web-frontend.rule=Host(`rekkoo.com`) || Host(`www.rekkoo.com`)"
      - "traefik.http.routers.rekkoo-web-frontend.entrypoints=websecure"
      - "traefik.http.routers.rekkoo-web-frontend.tls=true"
      - "traefik.http.routers.rekkoo-web-frontend.service=rekkoo-web-frontend"
