# docker-compose.staging.yml
version: '3.8'

services:
  app:
    image: rekkoo-app-staging-${CIRCLE_BRANCH}:latest
    container_name: rekkoo-staging-${CIRCLE_BRANCH}
    pull_policy: never
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo-staging-${CIRCLE_BRANCH}.loadbalancer.server.port=80"
      - "traefik.http.routers.rekkoo-staging-${CIRCLE_BRANCH}.rule=Host(`staging.rekkoo.com`) && Query(`remote=${CIRCLE_BRANCH}`)"
      - "traefik.http.routers.rekkoo-staging-${CIRCLE_BRANCH}.entrypoints=websecure"
      - "traefik.http.routers.rekkoo-staging-${CIRCLE_BRANCH}.tls=true"
      - "traefik.http.routers.rekkoo-staging-${CIRCLE_BRANCH}.tls.certresolver=letsencrypt"
