services:
  app:
    image: rekkoo-app-staging-${SAFE_BRANCH_NAME}:latest
    container_name: rekkoo-staging-${SAFE_BRANCH_NAME}
    networks:
      - proxy
    environment:
      - VITE_API_URL=${VITE_API_URL}
    pull_policy: never
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.rekkoo-staging-${SAFE_BRANCH_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.rekkoo-staging-${SAFE_BRANCH_NAME}.rule=Host(`staging.rekkoo.com`)"
      - "traefik.http.routers.rekkoo-staging-${SAFE_BRANCH_NAME}.entrypoints=websecure"
      - "traefik.http.routers.rekkoo-staging-${SAFE_BRANCH_NAME}.tls=true"
      - "traefik.http.routers.rekkoo-staging-${SAFE_BRANCH_NAME}.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true
