# .circleci/config.yml
version: 2.1

orbs:
  slack: circleci/slack@4.12.5

executors:
  node-docker:
    docker:
      - image: cimg/node:20.0
    resource_class: medium

jobs:
  build-and-deploy:
    executor: node-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image..."
            docker build -t rekkoo-app:${CIRCLE_SHA1} \
              --build-arg VITE_API_URL=${VITE_API_URL} .
            docker tag rekkoo-app:${CIRCLE_SHA1} rekkoo-app:latest
      - run:
          name: Save Docker image
          command: |
            echo "Saving Docker image..."
            mkdir -p /tmp/docker-images
            docker save rekkoo-app:latest | gzip > /tmp/docker-images/rekkoo-app.tar.gz
      - add_ssh_keys:
          fingerprints:
            - ${HETZNER_SSH_KEY_FINGERPRINT}
      - run:
          name: Copy files to server
          command: |
            echo "Creating directories on remote server..."
            ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} 'mkdir -p /home/rekkoo/web'
            
            echo "Copying Docker image and config files..."
            scp -o StrictHostKeyChecking=no \
              /tmp/docker-images/rekkoo-app.tar.gz \
              docker-compose.yml \
              docker-compose.prod.yml \
              ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:/home/rekkoo/web/
            
            echo "Creating .env file..."
            echo "VITE_API_URL=${VITE_API_URL}" | ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} 'cat > /home/rekkoo/web/.env'
      - run:
          name: Deploy to Hetzner
          command: |
            echo "Starting deployment to Hetzner..."
            ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "
              cd /home/rekkoo/web && \
              echo 'Loading Docker image...' && \
              gunzip -c rekkoo-app.tar.gz | docker load && \
              echo 'Starting containers...' && \
              docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d && \
              echo 'Cleaning up...' && \
              rm rekkoo-app.tar.gz && \
              echo 'Container status:' && \
              docker compose -f docker-compose.yml -f docker-compose.prod.yml ps
            "
            echo "Deployment completed"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy:
          context:
            - hetzner-deploy-secrets
            - slack-secrets
            - rekkoo-secrets
          filters:
            branches:
              only: main
