# .circleci/config.yml
version: 2.1

orbs:
  slack: circleci/slack@4.12.5
  docker: circleci/docker@2.1.1

executors:
  node-docker:
    docker:
      - image: cimg/node:20.0
    resource_class: medium

jobs:
  build-and-deploy:
    executor: node-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # Fixed Docker authentication
      - run:
          name: Docker Login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build and Push Docker image
          command: |
            # Build the image
            docker build -t ${DOCKER_USER}/rekkoo-app:${CIRCLE_SHA1} \
              --build-arg VITE_API_URL=${VITE_API_URL} .
            # Push to Docker Hub
            docker push ${DOCKER_USER}/rekkoo-app:${CIRCLE_SHA1}
            # Tag as latest
            docker tag ${DOCKER_USER}/rekkoo-app:${CIRCLE_SHA1} ${DOCKER_USER}/rekkoo-app:latest
            docker push ${DOCKER_USER}/rekkoo-app:latest
      - add_ssh_keys:
          fingerprints:
            - ${HETZNER_SSH_KEY_FINGERPRINT}
      - run:
          name: Create production env file
          command: |
            echo "Creating .env file on remote server..."
            echo "VITE_API_URL=${VITE_API_URL}" | ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} 'cat > /home/rekkoo/web/.env'
            echo ".env file created successfully"
      - run:
          name: Copy Docker Compose files
          command: |
            echo "Copying Docker Compose files..."
            ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} 'mkdir -p /home/rekkoo/web'
            scp -o StrictHostKeyChecking=no \
              docker-compose.yml \
              docker-compose.prod.yml \
              ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:/home/rekkoo/web/
      - run:
          name: Deploy to Hetzner
          command: |
            echo "Starting deployment to Hetzner..."
            # Export the image name for docker-compose
            export DOCKER_IMAGE="${DOCKER_USER}/rekkoo-app:${CIRCLE_SHA1}"
            # Pass the image name to the remote server
            ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "
              export DOCKER_IMAGE=${DOCKER_IMAGE} && \
              cd /home/rekkoo/web && \
              docker compose -f docker-compose.yml -f docker-compose.prod.yml pull && \
              docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d && \
              docker compose -f docker-compose.yml -f docker-compose.prod.yml ps
            "
            echo "Deployment completed"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy:
          context:
            - hetzner-deploy-secrets
            - slack-secrets
            - rekkoo-secrets
            - do-secrets
          filters:
            branches:
              only: main
