# .circleci/config.yml
version: 2.1

orbs:
  slack: circleci/slack@4.12.5

executors:
  node-docker:
    docker:
      - image: cimg/node:20.0
    resource_class: medium

commands:
  deploy:
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            # Sanitize branch name for Docker
            SAFE_BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | tr '/' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
            echo "Safe branch name: ${SAFE_BRANCH_NAME}"
            
            echo "Building Docker image for << parameters.environment >>/${SAFE_BRANCH_NAME}..."
            docker build -t rekkoo-app:${CIRCLE_SHA1} \
              --build-arg VITE_API_URL=${VITE_API_URL} .
            docker tag rekkoo-app:${CIRCLE_SHA1} rekkoo-app-<< parameters.environment >>-${SAFE_BRANCH_NAME}:latest
      - run:
          name: Save Docker image
          command: |
            SAFE_BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | tr '/' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
            echo "Saving Docker image..."
            mkdir -p /tmp/docker-images
            docker save rekkoo-app-<< parameters.environment >>-${SAFE_BRANCH_NAME}:latest | gzip > /tmp/docker-images/rekkoo-app.tar.gz
      - add_ssh_keys:
          fingerprints:
            - ${HETZNER_SSH_KEY_FINGERPRINT}
      - run:
          name: Deploy to Hetzner
          command: |
            SAFE_BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | tr '/' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
            DEPLOY_DIR="/home/rekkoo/web-<< parameters.environment >>/${SAFE_BRANCH_NAME}"
            
            echo "Starting deployment to ${DEPLOY_DIR}..."
            ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "
              mkdir -p ${DEPLOY_DIR}
            "
            
            scp -o StrictHostKeyChecking=no \
              /tmp/docker-images/rekkoo-app.tar.gz \
              docker-compose.yml \
              docker-compose.<< parameters.environment >>.yml \
              ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST}:${DEPLOY_DIR}/

            ssh -o StrictHostKeyChecking=no ${HETZNER_DEPLOY_USER}@${HETZNER_VPS_HOST} "
              cd ${DEPLOY_DIR} && \
              echo 'Loading Docker image...' && \
              gunzip -c rekkoo-app.tar.gz | docker load && \
              echo 'Creating .env file...' && \
              echo 'VITE_API_URL=${VITE_API_URL}' > .env && \
              echo 'Starting containers...' && \
              CIRCLE_BRANCH=${SAFE_BRANCH_NAME} \
              DEPLOY_ENV=<< parameters.environment >> \
              docker compose -f docker-compose.yml -f docker-compose.<< parameters.environment >>.yml up -d && \
              echo 'Cleaning up...' && \
              rm rekkoo-app.tar.gz && \
              echo 'Deployment completed for ${SAFE_BRANCH_NAME} to << parameters.environment >>'
            "
jobs:
  deploy-prod:
    executor: node-docker
    steps:
      - deploy:
          environment: prod

  deploy-staging:
    executor: node-docker
    steps:
      - deploy:
          environment: staging

  deploy-dev:
    executor: node-docker
    steps:
      - deploy:
          environment: dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-prod:
          context:
            - hetzner-deploy-secrets
            - slack-secrets
            - rekkoo-secrets
          filters:
            branches:
              only: main
      - deploy-staging:
          context:
            - hetzner-deploy-secrets
            - slack-secrets
            - rekkoo-secrets
          filters:
            branches:
              ignore:
                - main
                - /.*dev.*/  # Ignore branches containing 'dev'
      - deploy-dev:
          context:
            - hetzner-deploy-secrets
            - slack-secrets
            - rekkoo-secrets
          filters:
            branches:
              only: /.*dev.*/  # Only run for branches containing 'dev'
