const TermsOfService = () => {
  return (
    <div>
      <div>
        <p>Terms of Service</p>
      </div>
      <div>
        Rekkoo, LLC

        TERMS OF USE

        Thank you for choosing Rekkoo, LLC (referenced herein as “Company,” “Rekkoo,” “we”, “us,” or “our”). This Terms of Use agreement (“Terms”) is a legal agreement between you and Rekkoo and governs your use of the Services. The “Services” means our application, website www.Rekkoo.com, and any other website, social media pages, app, or other digital medium owned or operated by the Company (together, the “App”), as well as any and all products and services provided to you by Rekkoo. By using our Services, you or your business (also “you” or “your” or “their” or “user”) agree to be bound to these Terms, and to the extent such acceptance by you is made on behalf of any other individual, entity, or organization, you represent and warrant you are authorized to bind such other individual, entity, or organization to these Terms.

        BEFORE ACCESSING THE SERVICES, PLEASE READ THESE TERMS CAREFULLY, AS THEY (AMONG OTHER THINGS) LIMIT THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF A DISPUTE.

        BY USING OUR SERVICES, INCLUDING CREATING AN ACCOUNT, DOWNLOADING ANY APP WE MAY OFFER, ENTERING A CONTEST OR SPECIAL EVENT WE OFFER, AND/OR COMPLETING A PURCHASE WITH US, YOU AGREE TO BE LEGALLY BOUND BY ALL TERMS AND CONDITIONS HEREIN. YOUR ACCEPTANCE OF THESE TERMS CREATES A LEGALLY BINDING CONTRACT BETWEEN YOU AND Rekkoo. IF YOU DO NOT AGREE WITH ANY ASPECT OF THESE TERMS, THEN DO NOT USE THE SERVICES.

        Privacy Notice. By accessing or using our Services you also acknowledge having read our Privacy Notice, which contains details relating to our collection, use, and disclosure of your Personal Information (as defined therein). By accessing our Services, you represent and warrant that: (a) you have not been previously suspended or removed from the Services; (b) you do not have more than one Account (defined below) with us and (c) you have the full power and authority to enter into these Terms.
        Individual Features. When using the Services, you will be subject to any additional posted guidelines or rules applicable to specific services, offers, and features we may communicate from time to time (“Guidelines”). All such Guidelines are hereby incorporated by reference into these Terms. Please note that additional and/or different conditions and terms of use may apply to media, contests, competitions, products, or services provided through one or more of our partners or business associates, and you should refer to those before using such.
        Modification. We may make modifications, deletions, and/or additions to these Terms (“Changes”) at any time. Changes will be effective: (a) thirty (30) days after we provide notice of the Changes, whether such notice is provided via the Services or through other user interfaces such as the email, address, or phone number you have provided to us; or (b) when you opt-in or otherwise expressly agree to the Changes or a version of these Terms incorporating the Changes, whichever comes first.
        Orders and Accounts.
        For some aspects of our Services, you may need to or be able to create a personal profile containing preferences and other information that you voluntarily provide to us and/or register an account with us (“Account”). In doing so, or in connection with our Services generally, you may need to represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent (as applicable) to allow any of your minor dependents to use the Services. You may also need to provide a valid email address and password or add shipping and billing information to place orders.
        All information that you provide to Rekkoo or its vendors, agents, associates, or partners, including your payment card or financial account information, is subject to Rekkoo’s Privacy Notice and/or the respective third-party privacy notice. You are responsible for keeping your information up to date. Each Account, and the rights and privileges provided to Account holders, is personal and non-transferable. If you make a purchase and/or create an Account with us, you agree to: (a) provide accurate, current, and complete information about you as may be prompted by any signup, login, checkout, and/or registration forms associated with our App or our vendors for any Account (“Registration Data”); (b) maintain the security of your password and identification as such may be required; (c) maintain and promptly update the Registration Data, and any other information you provide to us, to keep it accurate, current, and complete throughout the duration of any transaction; (d) accept all risks of unauthorized access to the Registration Data and any other information you provide to us; and (e) notify us immediately of any unauthorized use of information you provide to us, including your Registration Data or of any other breach of security regarding your transactions with us.
        As an Account holder in connection with any transactions with us, you agree to receive emails or texts promoting any special offer(s), including third party offers. We (or our designated provider) may from time to time send you our newsletter and similar communications. If purchases are available without registration, such guest purchasers also may have the option to agree to receive emails promoting special offer(s), our newsletter, and similar communications. Account holders and guest purchasers may opt-out from receiving special promotions or our newsletter by opting to unsubscribe as may be provided in the applicable email correspondence. You cannot opt-out of certain emails regarding transactions you enter into with us.
        Certain Services may be available exclusively online through the App. Certain Services may have limited quantities and may be subject to greater restrictions regarding any availability, return, or exchange. We reserve the right, but are not obligated, to limit sales or access to any person, geographic region, or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any Services that we offer. All descriptions or pricing for Services are subject to change at any time without notice, at our sole discretion. We reserve the right to discontinue any Services at any time. Any offer for any Services made on our App is void where prohibited.
        We reserve the right to refuse any request or order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household, or per order. These restrictions may include orders placed by or under the same customer information, the same payment card or financial account, and/or orders that use the same billing and/or shipping address. In the event we make a change to or cancel a request or an order, we may attempt to notify you by contacting the email and/or billing address and/or phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers, or distributors.
        Billing and Payments.
        The price of all Services is payable in full before delivery. All sales and any other fees are in U.S. dollars. If you wish to cancel or modify a purchase, you may email us at hello@Rekkoo.com , however, any amounts charged to or paid by you prior to such modification or cancellation request may not be refunded and communication may not impact any order for which you have already been charged, depending on the state of the order. It is your responsibility to keep your payment method up-to-date, as well as to cancel your Account (as applicable).
        We may change the price of, introduce new, or remove Services from time to time and may communicate changes to you in advance. By continuing to use the App purchase options after the effective date of a price change, you indicate your acceptance of such change. Please make sure you read any notifications of price changes carefully.
        Payment processing for our Services is provided directly by us or by one or more third party payment processors as we may designate from time to time (“Payment Processor”). Rekkoo does not collect or store your payment card information. You can find out more about our privacy practices in our Privacy Policy and more about our Payment Processor’s privacy practices by viewing our Payment Processor’s privacy notice at https://www.apple.com/legal/privacy/data/en/app-store/ or https://policies.google.com/privacy, as may be applicable. By providing a payment card or other payment method accepted by our Payment Processor or us, you represent and warrant that you are authorized to use the designated payment method and that you authorize our Payment Processor to charge or debit your payment method for the total amount of your transaction and any applicable fees (including any applicable taxes and other charges). If the payment method you provide cannot be verified, is invalid, or is otherwise not acceptable, your transaction(s) with us and any Services you have requested may be suspended or cancelled. You must resolve any problem we or our Payment Processor encounters in order to proceed with your transaction, complete your purchase, or to receive any Services.
        International Access. International Access. The Services may be accessed from countries other than the United States. However, at this time, only certain Services may be available in identified international locations. If you access and use our Services outside the United States, you are responsible for complying with your local laws and regulations, and you consent to the processing, transfer, and storage of information about you in and to the United States and other countries, where you may not have the same rights and protections as you do under local law. We make no representation that any part of our Services are appropriate or available for use in other locations.
        Ownership; Proprietary Rights. The App is owned and operated by Rekkoo. The content, visual interfaces, information, graphics, design, compilation, computer code, products, software, website, App, and all other offerings and elements thereof that are provided by Rekkoo (“Rekkoo Materials”) are protected by United States copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws. All Rekkoo Materials are the proprietary property of Rekkoo or its subsidiaries or affiliated companies and/or third-party licensors, or as otherwise noted in connection therewith. All trademark, service mark, and trade name rights mentioned on the App or in connection with the products or services offered are the property of their respective owners. Users may not download, use, export, or re-export any content posted including any Rekkoo Materials utilized or available in connection with the App in violation of any applicable laws or regulations, including, without limitation, United States export laws, regulations, and controls. Except as expressly authorized by Rekkoo, you agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, infringe upon, or otherwise make unauthorized use of the Rekkoo Materials. Prior written permission to use, reproduce, or reprint any of the Rekkoo Materials (or portion thereof) or other information or materials used for the Services must be obtained from the owner for any commercial use. Any unauthorized use of the Rekkoo Materials may be in violation of copyright, trademark, and other applicable laws and could result in criminal or civil penalties. To notify Rekkoo of any suspected infringement of copyright, trademark, or other rights, please see the information contained herein regarding the Digital Millennium Copyright Act (“DMCA”) procedures, and contact us at hello@Rekkoo.com .
        Errors, Inaccuracies, and Omissions. Occasionally, there may be information provided via the Services that contains errors, inaccuracies, distortions, or omissions that may relate to product descriptions, displays, pricing, promotions, offers, and availability of Services. This App may also contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We have made every effort to display as accurately as possible the colors and images of our products and content that appear on the App. We cannot guarantee that your computer monitor’s display of any color will be accurate. The Rekkoo Materials should never be relied upon as the sole basis for making any decisions to purchase Services from Rekkoo. We and our third-party providers, vendors, agents, associates, or partners will not be liable for any purchase decisions made based on the Rekkoo Materials. Any reliance on the Rekkoo Materials is at your own risk, and you assume any and all risks associated with your purchase decisions. We reserve the right to correct any errors, inaccuracies, distortions, or omissions and to change or update information or cancel orders if any information on the App is inaccurate at any time without prior notice (including after you have submitted your order), but we have no obligation to update any information on our App. You agree that it is your responsibility to monitor changes to our App.
        Third Party Sites. These Terms apply to our Services. Our Services may include advertisements or other links that allow you to access web sites or other online services that are owned and operated by third parties. These links may also allow you to access our Services through a third-party account. We and our third-party providers, affiliates, agents, and licensors may be active investors in businesses related to or mentioned via our Services and may or may not have open investment positions in those businesses. You assume any and all risk associated with your purchase decisions irrespective of whether we or our third-party providers, affiliates, agents, or licensors hold positions in products mentioned via our Services. You acknowledge and agree that Rekkoo (and its owners, officers, employees, and agents) is not responsible and shall have no liability for the content of such third-party sites, and products or services made available through them, or your use of or interaction with them. If provided, you should review the terms and conditions of any linked websites or resources carefully.
        Third-Party Services. The App may include features or functionality that interoperate with online services operated by third parties (such services, “Third-Party Services”), such as to pay for products through a Third-Party Service, pursuant to agreements between Rekkoo and the operators of such Third-Party Services (such agreements, “Third-Party Agreements” and such operators, “Operators”) or through application programming interfaces or other means of interoperability made generally available by the Operators (“Third-Party APIs”) which Rekkoo does not control. Third-Party Agreements and Third-Party APIs (and the policies, terms, and rules applicable to Third-Party APIs) may be modified, suspended, or terminated at any time. You acknowledge and agree that Rekkoo is not responsible and shall have no liability for the content of such third-party sites, products, or services made available through them, or your use or interaction with them. You should review the terms and conditions of any linked websites carefully.
        Prohibited Uses.
        As a condition of your use of the App, Rekkoo Materials, or our Services, you will not use such for any purpose that is unlawful or prohibited by these Terms. Access to the Rekkoo Materials, Services, or the App from locations where such access is illegal is strictly prohibited. You are responsible for complying with all local rules, laws, and regulations including, without limitation, rules about intellectual property rights, the internet, technology, data, email, payments, or privacy.
        Except as expressly permitted by Rekkoo, any use of any of the Rekkoo Materials for unauthorized or commercial purposes is strictly prohibited.
        You may not use the App in any manner that in our sole discretion could damage, disable, overburden, or impair it or interfere with any other’s use of the App or our Services. You may not intentionally interfere with or damage the operation of the App or any user’s enjoyment of it, by any means, including uploading or otherwise disseminating viruses, worms, or other malicious code. You may not remove, circumvent, disable, damage, or otherwise interfere with any security-related features of the App, features that prevent or restrict the use or copying of any content accessible through the App, or features that enforce limitations on the use of the same. You may not attempt to gain unauthorized access to the App, or any part of it, other accounts, computer systems or networks connected to the App, or any part of them, through hacking, password mining, or any other means, or interfere or attempt to interfere with the proper working of the App or any activities conducted on or in connection with the same. You may not obtain or attempt to obtain via the Services or Rekkoo Materials any materials or information through any means not intentionally made available through the App. You agree neither to modify the App in any manner or form, nor to use modified versions of such, including (without limitation) for the purpose of obtaining unauthorized access to the App or our Services. Any resale or commercial use of the App, Rekkoo Materials, or our Services is prohibited, as is the distribution, public performance, or public display of any Rekkoo Materials; the sending of any junk or unsolicited mail to other users of the App, including, but not limited to, unsolicited or unauthorized advertising, promotional materials or other solicitation material, bulk mailing of commercial advertising, email, junk mail, spam, chain letters, informational announcements, charity requests, petitions for signatures, or other form of solicitation; the collecting or storing any personal information from other users of the App; and any use of our App, Rekkoo Materials, or Services, other than for their intended purpose.
        The App may contain robot exclusion headers. You agree that you will not use any robot, spider, scraper, crawler, or other manual or automated device, tool, process, means, or interface not expressly authorized by us to data mine, access, interfere with, or scrape the App or our Services for any purpose without our express written permission or bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the App or our Services.
        You may not utilize framing techniques to enclose any trademark, logo, or other Rekkoo Materials without our prior, express, written consent. You may not use any metatags or any other “hidden text” utilizing Rekkoo’s name or trademarks without our prior, express, written consent.
        You may not deep-link to the App and shall upon notice from Rekkoo promptly remove any links that Rekkoo finds objectionable in its sole discretion. You may not use any Rekkoo logos, graphics, or trademarks as part of the link without our prior, express, written consent.
        You may not use the Services or Rekkoo Materials for any illegal or unauthorized purpose, or engage in, encourage, or promote any activity that violates these Terms.
        Any use of our App, Rekkoo Materials, or Services other than as specifically authorized in these Terms, without our prior written permission, including inclusion in automated decision-making technology, machine learning, training, profiling tools, and/or artificial intelligence (“AI”) without our express prior written consent is strictly prohibited and, without limiting any other right or remedy Rekkoo (or its owners, officers, employees, vendors, agents, associates, suppliers, and/or partners) may have, will immediately terminate any license or rights granted herein to you. Such unauthorized use may also violate applicable laws including, but not limited to, copyright and trademark laws and applicable communications regulations and statutes. Rekkoo expressly prohibits and opts out of any text and data mining of the App (including content posted that is available in connection with the App), Rekkoo Materials or Services to the full extent permitted by applicable law in all relevant jurisdictions. Upon notice from Rekkoo, you agree to promptly remove any links or content associated with our App or Services that we find objectionable in our sole discretion. We have the right to terminate the access, orders and/or Accounts of users who we believe in good faith to be violating any laws whatsoever. Unless explicitly stated herein, nothing in these Terms will be construed as conferring any license to intellectual property rights, whether by estoppel, implication, or otherwise.
        Information. In order to access certain aspects of the App or our Services, you may be required to create an Account and/or provide specific information. All information you submit, including Registration Data, must be truthful. Any Account access codes or passwords provided should be safeguarded at all times. You are responsible for the security of your Registration Data and/or Account (if any) and access codes and passwords and will be solely liable for any use or unauthorized use of the App under such access codes or passwords. We may suspend or terminate your access at any time with or without notice. To understand how we use information collected from you, please read our Privacy Notice.
        User Communications. Under these Terms, including in connection with any Account, you consent to receive communications from Rekkoo electronically, including via email and/or texts. Such communications may include notices about your Account (e.g., payment authorizations, password changes, and other transactional information or notices), and you should maintain copies of electronic communications from us by printing a paper copy or saving an electronic copy. We may communicate with you by email or by posting notices on the App. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. Our Services, including social media pages or Apps connected to Rekkoo, may allow you or other users to post, link, store, or otherwise make available a wide variety of information, text and/or other materials to others (“User Content”). You are solely responsible for your use of User Content and features and use it at your own risk. By posting any User Content, you represent and warrant that you have the lawful right to distribute and reproduce your User Content. By using any User Content, you agree not to post, upload to, transmit, distribute, store, create or otherwise publish through our Services any of the following:
        User Content that is unlawful, libelous, defamatory, obscene, pornographic, harassing, threatening, invasive of privacy or publicity rights, deceptive, fraudulent, or otherwise objectionable (as determined in our reasonable discretion);
        User Content that would constitute, encourage, or provide instructions for a criminal offense, violate the rights of any other or that would any local, state, national, or international law;
        User Content that may infringe any patent, trademark, trade secret, copyright, or other intellectual or proprietary right of any other;
        User Content that impersonates any person or entity or otherwise misrepresents your affiliation with a person or entity; or that provides private information of any third-party including addresses, phone numbers, email addresses, Social Security numbers, and similar information;
        User Content that, in our sole judgment, is objectionable or that restricts or inhibits any other person from using and benefiting from our App, including, without limitation, User Content that contains or installs any viruses, worms, malware, Trojan horses, or other harmful or destructive content;
        User Content that is spam, is machine-, AI-, or randomly-generated, or contains unethical or unwanted or irrelevant (in our sole discretion) commercial content, or that furthers unlawful acts (such as phishing) or misleads recipients as to the source of the material (such as spoofing);
        User Content that does not comply strictly with any carrier agreements and terms associated with your mobile device; and
        User Content that attempts to or does disrupt the App or Services.
        We may from time to time provide interactive Services, including, without limitation: user-maintained help website, chat rooms, and bulletin boards. Where we do provide any interactive service, we will attempt to provide clear information to you about the kind of service offered, if it is moderated and what form of moderation is used (including whether it is human or technical). We will do our best to assess any possible risks for users from third parties when they use any interactive service provided on our App, and we will decide in each case whether it is appropriate to use moderation of the relevant service (including what kind of moderation to use) in light of those risks. However, we are under no obligation to oversee, monitor, or moderate any interactive service we provide on our App, and we expressly exclude our liability for any loss or damage arising from the use of any interactive Service we offer by a user in contravention of our content standards, whether the service is moderated or not.

        Mobile App.
        Rekkoo may provide Services through a mobile app (the “App”), including, but not limited to, an App developed for the Apple Inc. (“Apple”) and Alphabet Inc. (“Android”) mobile platforms. The App is considered an extension of the App, is included in the definition of such, as is subject to these Terms, along with any content contained therein. The App may collect Personal Information from you. Please refer to the Privacy Notice for how we handle such Personal Information.
        The App is licensed to you on a limited, non-exclusive, non-transferrable, non-sublicensable basis, solely to be used in connection with the Services for your private, personal, non-commercial use, subject to all the terms and conditions of these Terms as they are applicable to the Services. You will only use the App in connection with a device that you own or control.
        By using the App, you agree that we may communicate with you regarding Rekkoo by SMS, MMS, text message, or other electronic means to your mobile device and that certain information about your usage of the App may be communicated to us. In the event you change or deactivate your account information and/or Registration Data, you agree to promptly update your Rekkoo account information and Registration Data to ensure that you receive our communications.
        In order to use the App, your mobile device must satisfy certain system requirements. Those requirements can be found on the Apple and Google app marketplaces. Rekkoo may, from time to time in its sole discretion, make updates, modifications, supplements, or new versions of the App or this App available to you under these Terms for the purpose of, among other things, distributing bug fixes, patches, and feature improvements, or for any other reason. We highly recommend that you enable automatic updating on your mobile device or that you promptly install all updates as they appear. Rekkoo disclaims any and all liability relating to your failure to install any updates to the App. Notwithstanding the foregoing, Rekkoo does not have any obligation to provide any bug fixes, modifications, updates, or technical or end user support for the App.
        You and Rekkoo acknowledge that the Terms are concluded between you and Rekkoo only, and not with Apple or Google, and that Apple and Google are not responsible for the App or the content. You acknowledge and agree that Apple and Google have no obligation whatsoever to furnish any maintenance and support services with respect to the App. In the event of any failure of the App to conform to any appliable warranty, including those implied by law, you may notify Apple or Google of such failure; upon notification, Apple and Google’s sole warranty obligation to you will be to refund to you the purchase price, if any, of the App.
        You acknowledge and agree that Rekkoo, and not Apple or Google, is responsible for addressing any claims you or any third party may have in relation to the App. You acknowledge and agree that in the event of any third-party claim that the App or your possession and use of the App infringes that third party’s intellectual property rights, Rekkoo, and not Apple or Google, will be responsible for the investigation, defense, settlement, and discharge of any such infringement claim. Both you and Rekkoo acknowledge and agree that, in your use of the App, you will comply with any applicable third-party terms of the agreement which may affect or be affected by such use.
        Both you and Rekkoo acknowledge and agree that Apple and Apple’s subsidiaries and Google and Google’s subsidiaries are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Apple and Google will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary hereof.
        Ownership of Feedback, Testimonials, and User Content.
        You are under no obligation to provide any reviews, comments, suggestions, ideas, enhancement requests, feedback, and recommendations regarding us or our Services (“Feedback”) to us. You hereby agree that Rekkoo alone (and its licensors, where applicable) shall own all right, title, and interest, including all related intellectual property rights, in and to any Feedback you provide to Rekkoo in any media regarding Rekkoo Materials, and accordingly hereby assign such to Rekkoo without any requirement for compensation or accounting therefor. You hereby waive any and all of your rights of droit moral and similar rights with respect to any Feedback.
        From time-to-time, Rekkoo may permit end-users to submit reviews and testimonials regarding certain of the Services, as well as biographical information associated with such end-users (collectively “Testimonials”). By submitting a Testimonial, you irrevocably grant to Rekkoo the right to use the Testimonial, or any portion thereof, in any and all forms of marketing and promotional material, whether now known or hereinafter developed for any and all uses. You certify to Rekkoo that everything you state in the Testimonial is true and an expression of your personal belief. You acknowledge and agree that: (a) at no time did Rekkoo provide you with any consultation, advice, or guidance with respect to the substance of the Testimonial; (b) you are not an employee, officer, or director of Rekkoo; (c) you are not an immediate family member of an employee, officer, or director of Rekkoo; and (d) you are not living in the same household with an employee, officer, or director of Rekkoo. You understand and agree that the Testimonial, in whole or in part, may be edited and/or dramatized, and that any part of the Testimonial may be used without compensation to you. You agree that no advertisement or other material incorporating or making reference to the Testimonial need be submitted to you for approval. Rekkoo shall be without liability to you whatsoever for any distortion or illusionary effect resulting from its publication of the Testimonial. You expressly release Rekkoo (and its owners, officers, employees, vendors, agents, associates, suppliers, and/or partners) from any and all claims that you have or may have for breach of right of publicity, invasion of privacy, defamation, copyright infringement, or any other claim or cause of action arising out of or in connection with any production, distribution, duplication, broadcast, exhibition, publication, advertisement, or promotion utilizing or incorporating the Testimonial, or any other use of the Testimonial whatsoever. You acknowledge and agree that Rekkoo shall not be liable for any causes of action or claims related to your decision to provide the Testimonial to Rekkoo.
        You also hereby grant Rekkoo a nonexclusive, royalty-free, fully-paid, perpetual, irrevocable, world-wide, assignable, licensable, and transferrable license to use and otherwise exploit (including for text and data mining purposes) any User Content or information other than Feedback provided by you or any other party relating to the Rekkoo Materials on or in any and all media (now known or hereafter developed) as Rekkoo (or any Rekkoo vendor, agent, associate, partner, or successor) deems necessary to its business, including in connection with providing the Services. This license survives termination of these Terms. Rekkoo reserves the right, and has absolute discretion, to remove, screen, or edit any Feedback or User Content posted or stored in connection with our Services at any time and for any reason without notice. You are solely responsible for creating backup copies of and replacing any User Content you post or store on our App or through our Services, at your sole cost and expense.
        You represent and warrant that: (a) you will obtain all rights and provide any disclosures to or obtain any consents, approvals, authorizations, and/or agreements from any employee or third party that are necessary for us to collect, use, and share Feedback or User Content you submit in accordance with these Terms and (b) no Feedback or User Content you submit to us infringes upon or violates any other’s intellectual property rights, privacy, publicity, or other proprietary rights.
        Availability of App.
        Rekkoo may make changes to or discontinue any of the media, contests, content, or App, or Services available at any time, for any reason, and without notice. Rekkoo makes no commitment to update the media, contests, content, App, or Services.
        Use of the Services requires an internet connection and may result in charges from your cellular or internet service provider(s). Rekkoo is not responsible for any such charges. Rekkoo is also not liable for any disruption, failure, or malfunction of the Internet or other service providers, or for any other situation or event that is out of Rekkoo’s direct control. Rekkoo (and its owners, officers, employees, vendors, agents, associates, suppliers, and/or partners) is not responsible for any acts or omissions of your cellular communication or Internet Service Providers, or unavailability or errors associated with their systems or services.
        Notice. Except as explicitly stated otherwise, legal notices shall be served by a user on Rekkoo’s national registered agent, or by Rekkoo to the email address you provide to Rekkoo during any purchase, communication, or Account registration process. Notice shall be deemed given 24 hours after a notice is sent by email, unless the sender is notified that the email address is invalid. You agree that any notices, agreements, disclosures, or other communications that we send you electronically will satisfy any legal communication requirements, including that such communications be in writing. Alternatively, in our sole discretion, we may give you legal notice by mail to the mailing address provided during the registration or purchase process via the App or as we may identify for you. In such case, notice shall be deemed given three (3) days after the date of mailing.
        Violations; Termination.
        You agree that Rekkoo, in its sole discretion and for any or no reason, may terminate access to or use of the Services by any Rekkoo user, member, or Account (or any part thereof) at any time. Rekkoo may also in its sole discretion and at any time discontinue providing access to the App or our Services, or any part thereof, with or without notice.
        In accordance with the Digital Millennium Copyright Act (“DMCA”) and other applicable laws, we have adopted a policy of terminating access to or use of the Services, in appropriate circumstances and at our sole discretion, in connection with any users or Account holders who are deemed to be repeat infringers. We may also at our sole discretion terminate or limit access to our Services and/or Accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement. Additionally, we reserve the right to limit access to our Services and/or terminate Accounts of any users, for reasons of our own discretion that we are not obligated to reveal, at any time.
        You agree that any termination of your access to the App or our Services or any Account you may have with us or portion thereof may be effected without prior notice, and you agree that Rekkoo (or its owners, officers, employees, vendors, agents, associates, suppliers, and/or partners) shall not be liable to you or any third-party for any such termination or loss or harm related to your inability to access or use our Services. Rekkoo does not permit copyright infringing activities on the App or in connection with Company DBA Materials. Rekkoo reserves the right to terminate access to the App and/or Services and remove all content submitted by any persons who are found to be repeat infringers. Any suspected fraudulent, abusive, or illegal activity that may be grounds for termination of your use of the App or our Services may be referred to appropriate law enforcement authorities.
        Rekkoo also reserves the right to access, read, preserve, and disclose any information we reasonably believe is necessary to (a) satisfy any applicable law, regulation, legal process, or governmental request, (b) enforce these Terms, including investigation of potential violations hereof, (c) detect, prevent, or otherwise address fraud, security, or technical issues, (d) respond to user support requests, or (e) protect the rights, property, or safety of Rekkoo, its users, and the public. Rekkoo also reserves the right to remove content alleged to be infringing another’s intellectual property rights without prior notice, at our sole discretion.
        These remedies are in addition to any other remedies Rekkoo may have at law or in equity. You agree that Rekkoo (or its owners, officers, employees, vendors, agents, associates, suppliers, and/or partners) shall not be liable to you or any third-party for any such termination.
        Disclaimers; No Warranties.
        Rekkoo takes no responsibility and assumes no liability for any user content that you or any other person or third-party posts or sends using the Service. You understand and agree that you may be exposed to user content that is inaccurate, objectionable, inappropriate for children, or otherwise unsuited to your purpose.
        YOU ARE SOLELY RESPONSIBLE FOR DETERMINING IF THE SERVICES ARE SUITABLE FOR YOUR USE. THE APP AND ANY MEDIA, SOFTWARE, SERVICES, PRODUCTS, APPLICATIONS, MATERIALS, AND/OR THIRD-PARTY CONTENT MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH OUR SERVICES ARE PROVIDED “AS IS” AND “AS-AVAILABLE” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, Rekkoo, AND ITS OWNERS, OFFICERS, EMPLOYEES, VENDORS, AGENTS, ASSOCIATES, SUPPLIERS, AND/OR PARTNERS, DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS. Rekkoo, AND ITS OWNERS, OFFICERS, EMPLOYEES, VENDORS, AGENTS, ASSOCIATES, SUPPLIERS, AND/OR PARTNERS, DO NOT WARRANT THAT THE FEATURES CONTAINED IN OR VIA THE APP OR SERVICES WILL BE ACCURATE, COMPLETE, RELIABLE, CURRENT, UNINTERRUPTED, OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE APP OR THE PROVIDER OR SERVER THAT MAKES THEM AVAILABLE IS FREE OF VIRUSES OR ANY OTHER HARMFUL COMPONENTS. YOU ASSUME THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE SERVICES.
        Rekkoo, AND ITS OWNERS, OFFICERS, EMPLOYEES, VENDORS, AGENTS, ASSOCIATES, SUPPLIERS, AND/OR PARTNERS, DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE APP OR OUR SERVICES IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT Rekkoo NOR ITS OWNERS, OFFICERS, EMPLOYEES, VENDORS, AGENTS, ASSOCIATES, SUPPLIERS, AND/OR PARTNERS) ASSUME THE ENTIRE COST OF ANY NECESSARY SERVICING, REPAIR, OR CORRECTION. YOU UNDERSTAND AND AGREE THAT YOU DOWNLOAD, OR OTHERWISE OBTAIN MEDIA, MATERIAL, OR OTHER DATA THROUGH THE USE OF THE APP OR SERVICES AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE WHATSOEVER THAT RESULTS FROM SUCH MATERIAL OR DATA. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.
        To the fullest extent permitted by applicable law, you release Rekkoo and its owners, officers, employees, vendors, agents, associates, suppliers, and/or partners from responsibility, liability, claims, demands, and/or damages (actual and consequential) of every kind and nature, known and unknown (including, but not limited to, claims of negligence), arising out of or related to disputes between users and the acts or omissions of third parties. You expressly waive any rights you may have under California Civil Code § 1542 as well as any other statute or common law principles that would otherwise limit the coverage of this release to include only those claims which you may know or suspect to exist in your favor at the time of agreeing to this release.
        Indemnification; Hold Harmless. You agree to indemnify and hold Rekkoo, and its owners, officers, employees, vendors, agents, employees, associates, suppliers, and/or partners (together the “Indemnified Parties”), harmless from any claims, losses, damages, liabilities, including attorney’s fees, arising out of your use or misuse of the App or our Services in violation of these Terms, violation of the rights of any other person or entity, or any breach of the foregoing representations, warranties, and covenants. Indemnified Parties each reserve the right, at their own expense, to assume the exclusive defense and control of any matter for which you are required to indemnify such and you agree to cooperate with such defense of these claims. Specifically, YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS THE INDEMNIFIED PARTIES AGAINST ANY LIABILITIES, DAMAGES, DEMANDS, LOSSES, CLAIMS, COSTS, FEES (INCLUDING LEGAL FEES), AND EXPENSES IN CONNECTION WITH ANY THIRD-PARTY LEGAL PROCEEDING TO THE EXTENT ARISING FROM OR ANY ACT OR OMISSION OF OR BY YOU IN RELATION TO PRODUCTS, SERVICES, USER CONTENT, OR YOUR BREACH OF THESE TERMS. Your indemnification obligations under this Section are contingent upon: (a) the relevant Indemnified Party/Parties providing you with prompt written notice of such claim (except that your indemnification obligations shall not be limited except to the extent they would be prejudiced by a delay); (b) the relevant Indemnified Party/Parties providing reasonable cooperation to you, at your expense, in the defense and settlement of such claim; and (c) you having sole authority to defend or settle such claim, provided, however, you shall obtain the relevant Indemnified Party/Parties’ written consent prior to entering any settlement which admits guilt or culpability on the part of the relevant Indemnified Party/Parties or requires the relevant Indemnified Party/Parties to take any action (such consent not to be unreasonably withheld).
        Limitation of Liability and Damages. UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL THE INDEMNIFIED PARTIES BE LIABLE TO YOU FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES THAT RESULT FROM YOUR USE OR THE INABILITY TO USE THE Rekkoo MATERIALS ON THE APP OR THE SERVICES THEMSELVES, OR ANY OTHER INTERACTIONS WITH Rekkoo, EVEN IF Rekkoo OR A Rekkoo AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN SUCH CASES, THE INDEMNIFIED PARTY’S LIABILITY WILL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW. IN NO EVENT SHALL THE INDEMNIFIED PARTIES’ TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE APP (WHETHER IN CONTRACT, TORT, WARRANTY, OR OTHERWISE) EXCEED THE AMOUNTS ACTUALLY PAID BY YOU TO Rekkoo IN THE MONTH IMMEDIATELY PRECEDING THE EVENTS GIVING RISE TO THE APPLICABLE CLAIM. THESE LIMITATIONS SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF ANY ITEMS SOLD TO YOU BY THIRD PARTIES OTHER THAN Rekkoo AND RECEIVED BY YOU THROUGH ANY LINKS PROVIDED ON THE APP. THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN Rekkoo AND YOU.
        Dispute Resolution. You and Rekkoo will negotiate in good faith to resolve expeditiously on a mutually acceptable negotiated basis between appropriate management personnel or individual for each any dispute between them that may arise. You and Rekkoo may, by mutual consent, retain an arbitrator to aid in their attempt to resolve any dispute. Costs of the arbitration will be borne equally by you and Rekkoo, except that you and Rekkoo will each be responsible for its own expenses. Should any dispute between you and Rekkoo not be resolved pursuant to this paragraph of these Terms, you and Rekkoo agree to submit to the exclusive jurisdiction of the courts located in New York, NY to resolve any dispute arising out of these Terms or your access to or use of the App or our Services, and you hereby consent and submit to the personal jurisdiction of such courts for the purposes of litigating any such action.
        YOU AND Rekkoo EACH AGREE THAT ANY CAUSE OF ACTION BROUGHT BY YOU AGAINST Rekkoo OR ANY OF ITS OWNERS, OFFICERS, EMPLOYEES, VENDORS, AGENTS, ASSOCIATES, SUPPLIERS, AND/OR PARTNERS ARISING OUT OF OR RELATED TO THESE TERMS OR THE APP AND/OR SERVICES OFFERED BY Rekkoo MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
        Class Action Waiver. YOU AND Rekkoo AGREE THAT YOU AND Rekkoo EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. UNLESS BOTH YOU AND Rekkoo AGREE OTHERWISE, ANY ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON’S OR PARTY’S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY’S INDIVIDUAL CLAIM(S).
        Miscellaneous.
        Minors. The App and Services are not intentionally directed to minors under the age of eighteen (18) years. Consistent with applicable law, we do not knowingly collect personal information from minors under the age of thirteen (13) years. If we learn that we have inadvertently obtained information in violation of applicable laws prohibiting collection of information from minors without such consent, upon proper notice, authority, and necessary confirmation of such, we will work to promptly delete this information.
        Governing Law. These Terms shall be governed by and construed in accordance with the laws of the State of New York without giving effect to any principles of conflicts of law. EACH OF YOU AND Rekkoo HEREBY EACH KNOWINGLY, VOLUNTARILY, AND INTENTIONALLY WAIVES ANY RIGHT IT MAY HAVE TO A TRIAL BY JURY IN RESPECT OF ANY LITIGATION (INCLUDING, BUT NOT LIMITED TO, ANY CLAIMS, COUNTERCLAIMS, CROSS-CLAIMS, OR THIRD-PARTY CLAIMS) ARISING OUT OF, UNDER OR IN CONNECTION WITH THESE TERMS. FURTHER, EACH OF YOU AND Rekkoo HEREBY CERTIFIES THAT NO REPRESENTATIVE OR AGENT OF THE OTHER HAS REPRESENTED, EXPRESSLY OR OTHERWISE, THAT THE OTHER WOULD NOT IN THE EVENT OF SUCH LITIGATION, SEEK TO ENFORCE THIS WAIVER OF RIGHT TO JURY TRIAL PROVISION. EACH OF YOU AND Rekkoo ACKNOWLEDGES THAT THIS SECTION IS A MATERIAL INDUCEMENT FOR EACH OF THEM, RESPECTIVELY, TO ENTER INTO AGREEMENT PURSUANT TO THESE TERMS.
        Force Majeure; Waiver. Rekkoo (or its owners, officers, employees, vendors, agents, associates, suppliers, and/or partners) is not liable or responsible, nor shall be deemed to have defaulted under or breached these Terms, for any failure to perform or delay in performing its obligations under these Terms due to an event of force majeure. An event of force majeure is any event or circumstance beyond Rekkoo's reasonable control, such as war, hostilities, act of God, earthquake, flood, fire, or other natural disaster, strike or labor conditions, material shortage, epidemic, disease, denial of service attack, government action, or failure of utilities, transportation facilities, or communication or electronic systems. A waiver of any breach of any provision of these Terms shall not be construed as a continuing waiver of other breaches of the same or other provisions of these Terms.
        Severability. If any provision of these Terms shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.
        Assignment. These Terms and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Rekkoo without restriction.
        Headings. The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and shall not be deemed to limit or affect any of the provisions hereof.
        Entire Agreement. These Terms, including the recitals hereto, as may be revised or supplemented via Guidelines or amendments in our discretion, is the entire agreement between us and you relating to the subject matter herein. Except as otherwise provided herein, these Terms are intended solely for the benefit of the parties hereto and are not intended to confer third-party beneficiary rights upon any other person or entity. All provisions which, by their nature, are intended to survive termination, including those with respect to payment obligations accruing prior to such termination will survive any termination of these Terms.
        Copyright Complaints. If you believe that anything on our App infringes upon any copyright which you own or control you may file a notification of such infringement with our Designated Agent as set forth below.
        Name of Agent Designated to receive notification of claimed infringement: Alfonso Cobo

        Full address of Designated Agent to which notification should be sent: 651 N Broad St., Suite 206, Middletown, DE 19709

        Telephone Number of Designated Agent: 213.260.1439

        Email Address of Designated Agent: hello@Rekkoo.com

        Please see 17 U.S.C. §512(c)(3) for the general requirements of a proper notification. You should note that if you knowingly misrepresent in your notification that the material or activity is infringing, you may be liable for any damages including, but not limited to, costs and attorneys’ fees, incurred by us or the alleged infringer as the result of our relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.

        Disclosures / Contact Information. The App is operated by Rekkoo, LLC, 651 N Broad St., Suite 206, Middletown, Delaware, 19709; hello@Rekkoo.com ; 213.260.1439. If you are a California resident, you may reach the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs via mail at 1625 North Market Blvd., Suite N112, Sacramento, CA 95834 or telephone at (916) 445-1254 or (800) 952-5210. Hearing impaired users can reach the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs at TDD (800) 326-2297 or TDD (916) 322-1700.


        Last Modified: November 29, 2024


      </div>

    </div>
  );
};

export default TermsOfService;
